### PR TITLE
Build tweaks & misc README tweaks

### PR DESCRIPTION
**Pull request by dwijnand**

### CODE REVIEW

**Comment by djspiewak** [comment]
I really hate vertical alignment, but I guess I'll tolerate it since it's a readme example and most people seem to prefer it.

Thanks for the tweaks!

**Comment by dwijnand** [comment]
Yeah I know :)

**Comment by dwijnand** [comment]
BTW you seem happy with vertical alignment in core/build.sbt.

**Comment by djspiewak** [comment]
SBT dependencies is literally the one and only exception I ever make. :-)

**Pull request merged**
