### PR TITLE
Added scala.js support, fixes #14

### LINKED ISSUE #14: Add Scala.js cross-build
There's nothing in core which is dependent on the JVM.  Or at least, there really should not be.  There's no reason why parseback could not be cross-published for scala.js.

### PR DESCRIPTION
**Pull request by m-sp**

### CODE REVIEW

**Comment by djspiewak** [comment]
Thanks for the contribution!  Quick question though…  Why does this necessitate removing the project-specific `build.sbt` files?

**Comment by m-sp** [comment]
as far as i understand it, sbt only uses *.sbt files in (sub-) project folders. but because of the scalajs sbt plugin the actual project folder for e.g. `core` is not `core` but `core/.js` and `core/.jvm` respectively and therefore the additional configuration in the sub folder is not used

**Comment by djspiewak** [comment]
Hrm.  Let me poke around with this a bit.  I would hate to lose the ability to organize subproject builds independently.  Scala.js support is more important than build organization, so that wins in the end, but maybe we can have both with a bit of trickery.

**Comment by m-sp** [comment]
one possibility would be to explicitly add the build.sbt to the project. e.g. something like:

```
lazy val core = crossProject
     .crossType(CrossType.Pure)
     .in(file("core"))
     .settings(
       name := "parseback-core",
       coursierSettings,
       bintraySettings,
       mimaSettings)
 .settingSets(AddSettings.sbtFiles(file("../build.sbt")))
```

the one thing that bothers me is the relative reference to the build.sbt file starting from `core/.jvm` and `core/.js`

**Comment by djspiewak** [comment]
@m-sp I tried a number of different tricks to try to get this to work (including the one you suggested).  Nothing worked.  :-(  So we're going with your implementation for now (everything in `project.sbt`) while I plead my case to Sébastien.

Thanks much for the contribution!

**Pull request merged**
